- hosts: ubuntu-aws
  gather_facts: False
  become: true

  tasks:
    - name: Apt update
      raw: apt-get update -qq
    - name: Installs python 2.7
      raw: apt-get install -qq python2.7 python-simplejson apt-transport-https ca-certificates
    - name: Installs docker
      shell: curl -sSL https://get.docker.com/ | sh
    - name: Adds user to docker group
      user: name=ubuntu groups=docker append=yes
    - name: Starts Jenkins
      command: docker run --name jenkins -d -p 80:8080 -p 50000:50000 -v /var/jenkins_home jenkins