---
- name: yum update
  yum: name=* state=latest
  ignore_errors: true

#- name: Add the yum repo yourself For version 6
#  command: tee /etc/yum.repos.d/docker.repo <<-EOF	[dockerrepo]	name=Docker Repository	baseurl=https://yum.dockerproject.org/repo/main/oraclelinux/6	enabled=1	gpgcheck=1	gpgkey=https://yum.dockerproject.org/gpg	EOF
#  ignore_errors: true

- name: install docker-engine
  yum: name=docker-engine state=latest
  ignore_errors: true